name: Apkpure workflow

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - name: check apk versions
        run: |
         gem install yadisk
         yadisk ${{ secrets.URL }}
         echo "ls $(ls)"
         
         
        
